sudo: false
language: node_js
node_js:
- node
install: npm install
script:
- npm test
- gulp
cache:
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: AWS_SECRET_ACCESS_KEY
  bucket: innovation-lab.cz
  skip_cleanup: true
  region: eu-central-1
  acl: public_read
env:
  global:
  - secure: O0rmIyzCxcoJScfMYRG2Z/zfKDBSmIOZr6twTLy+R+RQAXHfpvluLW26o+m8a3yZNwofVxdMbRzzZ1xvMILHySv+Sf1cw4Nj4eMb/Vw+U6NJiM9aj5jeBWsYL25Af0b2wonS7d8R5tCNaPS2ZZID+7sYIqrPfDBypaC70nc+ErIT5u5EXo5hDGCiP7O3Xgrayy5Jxfx/PAsB+Z61TDPgp/gTcCXPCFrmK/WUQk1gMSFChmGFHsXVs0U5iDAiBOmA9PTswGE3Wh6qAnNQkiA2ivbC6a8JLVgOrQ4hYd2QsrerJ0CXpzFjxI0TEkVL6Zw3u46UlF2ZFB3aXzV2oDTqavmuqImww6xiKPiEXF3iuWCin4VFnCTTn/s4T3irgC3+NIxQPARRXeseWGLh4s19aud1HFPDfPhZfMzgl2U/vOA0/tBhILLqcOx56i1rH+vUqw5/YEh000F047jEpI0TRtCs5RknExA0gzbWznn7AUzDlcXzWAvryO0tsiS6K0NpjtQXY8hawm355BkdxWsPXrdhrHsg4IVntGUJmApvU29ZfBiSl5z1KcdEVOzC4Efc/c0CQSNMRjtPxL0N1FzzqiALk33HuBrjBdz1jd7M/4Y4W7855uwuU91yvQih6BhQAqdKucSQleCSuq3pBKZmlhj2tYB2qy6OH1Id6weqtRQ=
  - secure: MW3UB/6Eo4ZzonORCp2SlNCeuMh2HcFkzVcT984GymdL+6j3kIv5BKeL0GX2idZ8cGmtP6kn5RBOrAAKkpUPrva5KjdsubmbRBCcT1ZfVTAC+KRuN4QnZtvfxUiT3f/T/OqV5wLVe5X8qkjekS/Z08SBUgFhHUQDZDj/EWgfUIPN9lsf4laE1AmDOikhJ6DcZBXDFpnwtuFT07/tsUhr/QOEGvyZbMiCZtQNbdi4P5ZFHAAJ3uwDWmRFbsVxKXf4dNXHUg1xlvuKiNtg3P26HD8RzuYnLOLt1lvtZCvsQBRE1ga/cQ8RXyQnnG0x7xuL5yXflKpEp+bAVO+D/wPDZnjxaW85W5GKlO8pBIssViYueE0LqKEnZaregAst/B876OiUScI4LVwZMEWauQ7uZe6Hs1RjTNRwfUvW0uIrWhgNLpOkbr0YVIgU6h4sCSLGMZqWBHw6cotZZ5k148qwdq4uX9jeH+hDX3u1JW8wQ1wmNRllh6fKt7tr2sXAVi7VH9nAsILLyIiRnTIdMku+RZk8J2FlBMEUJ2L5sJ0acYyz4Fker64W2T/6Fg1KkxczOrxbtA8c8zjyiwm0EzDrULAYGtGcMQ4MqlLwqgW1uabVRTt736xL0nTir+HrYm0RISDSc06tFfXKqSaH2ajWHfnGlUXIBMB+y85KDi10rug=
