sudo: false
language: node_js
node_js:
- node
install: npm install
script:
- npm test
- gulp
cache:
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: innovation-lab.cz
  skip_cleanup: true
  region: eu-central-1
  acl: public_read
env:
  global:
  - secure: ItmWXJ5Haf6qsTtKEO2ZyEvmKmNvZgQ9H6fAUBvzVy+Yahbz6cZVvmvC8dzJK0MT1PH+2t+fE+BlARr4qu61B9DRYH3MhKAQsMboBibTZiVo1VZdTNEOOGgHTVcICKvH8nFgD952Ey9nEEZK28dAY02EO7fnNchEW3TJt2dyAchVcoc4ICMfWi3s157/ZwiY52ThZ6JtHi8xpLnuSCBm18FbgYZ/ur1PZ5hWLohqtiKyXDB710l9soZUH8l0sxRlEqrWCFuncrL/Q9GBTkRNL4edJirFquzSXB4Nq36tGO8XOHaPmvN3yuklYCElb48RG1DGQbDg6/soj58No9Sc1cp1sr6Kt9WFJrUgtv/n9g+NgvzzZkSWxBM0MY3kU/1vzsIfDuq4a5Xg29i0uuu22wq8+3OaxFsB+U39gNdgk8M9HlYlU7Uxm1VogUrIkSvSdeiIQc62AQpS+2/oPv43lDnl0wbmuDYlUHp3wYEoaVOEtI/bIa9aoysh4zM6mtsjb2fosSscVFwhDtL1XVwiRNsTZQgi5hqn1rijl/IxrJpGhWTNNVCP3gQq/7Z0yg47kjY+5n7wXYPGLUh12DyNGaI6BRF86eT2RTRwryoDdLj723MG96p3qrrp5KCSrV2o3QAKaf5NSV4EHi9HsAmYAnkDzRFAH8EqXsxIis8UIKs=
  - secure: JUoKDkJCP8edzT3uDEDFvzAmCm3v6KI8+XYopl0I6A1Bf0/MX3hpJG/jtggN3yV5T42CztZTr12j1yQb5PGPuQX6T/0JizYFdNFmiy9pdRvN8fwwneK4vT7LHXFz3+8ZBgFnQp0hIM3Hh4qo/0ktJAkQ+aPDuaM68a8DBTr5IBzZSxzBP1tj1GoDMfxQQr8PpPulgxYm/b/pGwzQjtObUrLweQ1I9kGrOahJ/lSh0GUGHyPuGE930GcOdLy3ZnGSyZBR+WUzs+xvaPguZXpYPZkNoxohVUqKT6WrgrRXDmg/bb1DvQr77tPv2Zf/wMl20ST0tjjtknW8bHNbbFq6Q3C2AxbUHKCgd/H+zZvpvMW8sPvqzhUoGqLFXVXzyYf/p+P4DllmX+fUY8SkUUmGUyr1609NYx+J8HXZaYJchp+ni+TTbE4YE4diL61IeLCRpiuSMo+kAwTpLM2eu0u1/LzdTulTABYh4II68XYRsnutDLtIYsnq7s7dRlpTv09vCcERscT4e5r0STBv1PupKxv/0zk8BQLAb0zH8Z0ulAeM8wG0mEadmOt1kRdKvrRZFPG9tOB+x3OF0Zb5SqxSpWyAARyM1+/xRdTFLf4CzCpzE0gQmV+7DY4kd5qDheCDwV/OjiWg1Eji0i5oZ6QdLutwmWri3Udmh04c6+lgq4Y=
