sudo: false
language: node_js
node_js:
- node
install: npm install
script:
- npm test
- gulp
cache:
  directories:
  - node_modules
deploy:
  provider: s3
  bucket: innovation-lab.cz.s3-website.eu-central-1.amazonaws.com
  acl: public_read
  skip_cleanup: true
  region: eu-central-1
  access_key_id: $ac_key
  secret_access_key: $se_key