sudo: false
language: node_js
node_js:
- node
install: npm install
script:
- npm test
- gulp
- git clean -df
- git checkout -- .
cache:
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: AKIAJ3MWH4VLU7OLMTUQ
  secret_access_key:
    secure: fw5/4Dty1dYDVryraYG3Prt/lIRuf4J0fXuJNoLs+6SUFQVqehylqhupHP701fmdMlt3h/O2hL27r6CQu9EYuDL8bcZFTs12l8hcWYfxzyGx3UWGzUGfTBgQOMOPozVY5BeZI7o0X85lBdsgRQqX8l8lsZhA9rjqzm423rB8z+L4zFtBwesALOiTprPiVSNR6FBEXn0ePth8ovvpvF5kjxYBkQmMzMcCL82SlhDYhx/pqgmDzV/OwtUlErO7KbB/OxGTLN3UMPnEWaLcDJltWLBU6lbriPDIS7cWuB+8OmMR9tTaOqBtiHfE4xmA85Wkux5wwcmxXqjdcnfwdPEwcPz4gFSr3OtOd2WALl5R3Af9jFGeTbzzoEz8riXcxAfYb42EthY5uO1lx6jSEZM9Y3uz7BI4YyC4GpDkZRgHWuIyhYwqjcSNcBHx4rpfHkOTAnepu+sQ9Rs+lwedE+jrrZtgdKjraSgD1gN9Y9UEYsuXp7stN2Bt/D+m/2ro4dD1ugnbaBgkU1C5IU91fYUM9qLEjICMEPnW1US4AABuU8XfmIeuHWt0cLec4TXNf6DUg5fW3yMb/lFaCP7it3fTrez3md0Ne379V0V5OsQUXa9Q23vy07kYXXh5KfIBMoA2w9wmerna/WmrIZQaDUmtAVaDHWgVGemI4Wew4c317WU=
  bucket: innovation-lab.cz
  acl: public_read
  skip_cleanup: true
  region: eu-central-1
  on:
    repo: StanSiska/inno-lab-web
