sudo: false
language: node_js
node_js:
- node
install: npm install
script:
- npm test
- gulp
cache:
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: AKIAJ3MWH4VLU7OLMTUQ
  secret_access_key:
    secure: AYSqTvHB+N3hg7LlqEnulNShWYJ3ZAo1L6ljQA7sJk+IBVOsk77ciBiPXiDhs9JCXg8GZJDxZSueVMgWC4zLeFQ9DoYxCFY4rtHac78hdz2OGEZXX1/YgSPhncGUKr+2k4+JOwMGHmoHf39Gk2A4PJv5aEmd3RkNkS2/iWYZNn5p2nI+7aqiU6LIGNZ5DypmvPI3aNEAiaSWZwsoNWL+y8U40ZH1XOjrcmK6Bv4Cgxf2TZArl1HmdPgE8xLwtnoK2lPU9UcWWpakcXbwW6uZhLPZADHsL2RdY56/q66Jm6vCuUlb7k3+bRoHQtDV31zkmpYsPw1uf6rPDXkYXCwng7wm1YoGUWYI1Amw2tAYTfGCq3tHOfUtrkbXC7ZUiXmiLgcXXztxyBVuiqAM7NLSaTwhTMwaT40TTDerFxCt4KdUra03vzQh2NVDmzM4Ek/qEANuYkRha48Tz/AHbOKgCyfNX5u6n1tFagRAb6bwRehIRrgomVqfW4SqvqejfXjlVHjtxlfk2VK/D+LFhkL2c9v784yUG+lvjdbFHsYD1np9XkgreiIC4NBwGuomBGgiNnauCB4mXdmelEbRVjiPToqmRZJcZ63bbrp/jhwC6lNAfMwOquKWuL/zkujKzrtjqKArik5G6tRBWO79aUJAm8EzwiSnTmMEF5+O2ctctdY=
  bucket: innovation-lab.cz
  acl: public_read
  skip_cleanup: true
  region: eu-central-1
  local_dir: ./
  endpoint: innovation-lab.cz.s3-website.eu-central-1.amazonaws.com
  on:
    repo: StanSiska/inno-lab-web
