sudo: false
language: node_js
node_js:
- node
install: npm install
script:
- npm test
- gulp
cache:
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: AKIAJ3MWH4VLU7OLMTUQ
  secret_access_key:
    secure: gj7Sn3Jv+HcEYwFyTnMubTVXvo3QDNbSyK8Wq52yxXqLoZJr3bOqG7bkKF56mZHHSo7EQdKmRywGYwQnCkZZnd8QlA6xLNw+FQKlETwSEhVXCcC0sXzE3iuwCcqoirJaEk0uOaDF958YZN0qzU2ZTJCQWsrtFatZr2BH+d5l2d8gC4TuF2BlzExr4ymjUqongTqeNbLsexfHqdico6R9n7wuXv5goy9ujXisUh1z+LlUT/YGX8IAf18qkdMc0BS7G8ULGV6HedM5wv0d9LZD53yZSZ1K+jLf/HrTSfasr+meV9JbHga7oO4oHaEGqKwJ9RRUsdKFLiAYJRVBsB7opK1wNuPv6B8KlxktcKSQA7IeNQ8yGT1DTq5usiUoR+p9Eb5OI32DqSE59r1bK/VmTiFMXNZH1ClUrz70ZORC+b1/Q0mdZxGrF0U2Ng64wABVVV5EzC9j4zCvXXjIBteFKzFPZoEe3bZOIoMtGAz2o7yir+Ukz3/OZXMiMe11U7jHxXyGxMU7zbe33e3QGfLbQMievUmgmrk1gMeniSh/P0Y6Ll4o9j+ZXoD7wHlnRHA023YonO92Krk43/EAfX2dBuNXTBnON0eWmFQRKXtXuNnuT5EBPWBMZoP53mNTaJF/HvRS1jN+2CHpgy1n2/ZratuUZ8oP0ZYmUijwQBa/A7Y=
  bucket: innovation-lab.cz
  acl: public_read
  on:
    repo: StanSiska/inno-lab-web