sudo: false
language: node_js
node_js:
- node
install: npm install
script:
- npm test
- gulp
cache:
  directories:
  - node_modules

deploy:
  provider: s3
  access_key_id: access_key
  secret_access_key: secret_key
  bucket: "innovation-lab.cz"
  skip_cleanup: true
  region: eu-central-1
