sudo: false
language: node_js
node_js:
- node
install: npm install
script:
- npm test
- gulp
cache:
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: innovation-lab.cz
  skip_cleanup: true
  region: eu-central-1
  acl: public_read
env:
  global:
  - secure: Qp8czyIl6be791EN72anvF2P2pSIX/xa2KkRI58rMr0j0YY4wQsyZXBK+RU4saEnfHu6jl9twriUjz13KrQYfY/dbVMaxCXdLV4QqFFml5I8+LN4EfM8H1/Z4+nh5Vrd1peiIQuMoPuvhBr/6DDgq54Hqqum3MHL5087ue1a3DP01ignZuQzwgEOossrL/g6XjEP0rxrQziV6QB+mtDpEDrKOpO6gUAPAw8Qvd3GW+ETomtxpcG/utpRlB3eAQmgj/bhh5LXMDiKsGBZG111ub0fpgYruDsW+3l+i1yK1xcpysAWn2WELSPfxFIy1bmuthAC5oQTxnR1grGIc+uCX80Ri8OVdNwg7ro94xWLQ87B6vkN0+D0253+STxhNvNRTKXXCZPWpNBh87CKPPtZlndeKgM+npLzp/Thc/mhbLuzmSmsxvV3jx+p3+vMKLug5LuAw3EhnvMKptf+eVxgk3m48UKYbZI2aroz3g6CrQIqVNc0dqAuh4/cjppN2e+0U5EN2MbHLUM6cQ+3htQXrgDfACQRFBiqmD2Y1dvCu7C05Rer4rN2EoZj160MJ57d7z9aLREX+O0UCJAh8//lwewZRKTYh2m5i7lXKOiL1w6Dm8xP992nIpviG9O9VVmRH5F3tQyloyoy7G0ODKcSJGtjhMVb1ZQKaR7kDj6eFaY=
  - secure: AjzotPNaqjQhFwRO+9sl0E1UXdQV107JtIBf1uG6aXIF/Z/1nMhXYSvs3X2tkr6bjZHgfKbU0+6HIbY1DNT69Ac551Tz1QC0XmlMFuiY7l9hsrXzTrjeq0SCi306bwGgYS/a63upDqBWetzp0KoUNpCd46ZhgsikAGCRgm99g6o9QswAtezXssUbKSPf/4k1BBxE21dlwKRDzTDTYU5q2+djW3/7Kp2Y6c9Xd6Mj/gOxVO3SbIw0FvrUb3wMGx9aos74qO6pgsBb32DqykS/+eFQh8oIjUoCWqztuMw1iRg0HqgKQSuVx+JEtoZWGKRME+fq3JdVh3O2Wl/s6DCUsXEyAWJ6oXf5cltYl1DJaPeeUeKnlPlvZV7DlsQPnoo5zMMK6jYoOPKmie+Vjg74WOTuDd2pRzAqCQnKlzPrxNZHgmvTskmBKCcyHg0PUm1UqXbrz4nTkqmYvB/nlVYPOX5DNgPsPDNpETvzPdhKOssDsfqehJ0Qbd0WcutYNGJC2FJ3ADqmU2HGTSXGplwkn4JcGS4mB5dVA9V6gLMm5Jqhgu0FH4LFwqmFSljHXBFKVNMdXLf5P7V/DpX+XNJg0i7M90yIqcwXjObS2wvI0pRT7+BrPTsTqxt21m2WmAb7txL3P4ECBZQf/E6qKONYfYMgpZvSLM0f1SU3hZ1sa90=
