sudo: false
language: node_js
node_js:
- node
install: npm install
script:
- npm test
- gulp
cache:
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: innovation-lab.cz
  skip_cleanup: true
  region: eu-central-1
  acl: public_read
env:
  global:
  - secure: fS17j+oYIPO+nLwGbFlFke1TZBQA7J2x292YgD8oFnjcSr/NNh6UUx7KNbtF0jF6XX2h9Ck5aKzhuERosESUTSrSyGX6DhYHj4eb2ABdpLkJhgDNfAxPLwWhkNfIJ0onj90n9Y87JneoPQDcB8uWHenOjh4lhi2oVHeo4/8QNTSQXt+BAnkzGgIk76tpFdmGSNvgCJO8EAzz0TfLhxYxwisf3MqlZ+oIFXQBQONu/vWrRnri0iDxvyP62KJoj51WTHsZurwB1mjlbpWA6y6gjBXsq8APN+ImXSJxHqTnKaXQDosM1lvt33E6A+4Gu1bmcuCBTXRkF/XLLmTDjSf8G6uoTwzfrZa0HZw2twrjQf9ZWCfRSKmA5wv2/Ylvdui9oqoufAHf16JSRWx4OciSOvJuoVTIZ5daGru6SUXL4MHLYImkUiXygaRPy6Qy4U8lzJSqEbZRdAcvCyhqeQCtvaV3n0WoTWo1j9R8wFkDLNqlr0RcoR1lyC5QAnmmgwvFfXuxsQXe2bJF4B4tKgo1HMR9iMkFUH95M9I3mzJhx4+eq/thNAQxTgfxUsDgxAqXDrfCLz7rdJn4VdkzWRlpBJrlB/BlN4Xgt0YpGjZYvrFES/srEXYgRDHpkPzWVJGariaQzrUutB26fACHe3oU/yKMIzyOejqATy+t3S7Jbs4=
  - secure: N56znY8JVcVhcCuCkmCYPo4iXdcm9meBbVM6u3GLIinIUCcQr2Ka3rqJH1tCAlHEJXb05RGdBgwDJldwTlBybVuVI2kW7UfhEqWWXt4F3iqcMjKZqd+u/+8yXmqH0cQL5ypwPsSbB/IZsXERxq/hddOivkTpQHI7Diu87K898MK2NTd/w6SrJGq8DSva31T4IH/92l21lIkQgTtEXK7CZoWYCZZN5IBbZhKiE9uDvWP0Lhb5VkbUhdlm0wf5dyZWT2wE2UNTsfqFwIzgUdTDG9r3fVJVoHTPi0Twqv/YLD3OMeY84Dv2NEIT42M8pECUuiGXX5Za9CXHvaT3I6p+8zb8uUQlR8C1+HJdRht8Dm0FATYOyn7LQzJKVA8+q2842XHwkDUfn//d5IEQDyfJBx1wAH8s5J0a3uWfnNOnCjnowEEfN/Gw3cIGM7DIk8K6oAWfvCh/PMcAA5mbaqGgczbvqHNcUqIQ3M87cVd70sBZ02o1CHMXeQN+3hPow7dwX7SVZKKj9TUVEL4BGqdH1cMWT8YugAZaptnnPFgc9qZZIVZXZfWiAvy6T0vuc8D1sv3/QkyXU+gIuGU+vaXLCWeQfr52X7epugejnkT4IlRWUrtdMQFUmsAMRHFdKV0RKEE/2Anm6avUZQQak9Y3FF88WbB3K3EUZv/Emiig3XQ=
