version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory:  /home/circleci/innovation-lab-web
    steps:
      - checkout
      - run:
          name: Install Python and AWS-CLI
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install -y python-pip python-dev
            sudo pip install awscli
      - run: 
          name: Sync to S3 bucket
          command: aws s3 sync $CIRCLE_WORKING_DIRECTORY/ s3://innovation-lab.cz/ --region eu-central-1
