version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory:  /home/circleci/innovation-lab-web
    steps:
      - checkout
      - run:
          name: Install Python and AWS-CLI
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install -y python-pip python-dev 
            sudo pip install awscli

      - run:
          name: Install Node + npm
          command: |
            sudo curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            sudo apt-get install -y nodejs
            npm -v
            npm install 
            npm run build

      - run: 
          name: Sync to S3 bucket
          command: aws s3 sync $CIRCLE_WORKING_DIRECTORY/ s3://innovation-lab.cz/ --exclude "node_modules/*" --region eu-central-1
